#5.2 넘파이

배열 정의

In [ ]:
import numpy as np
a = np.array([[2,3],[5,2]])
a

array([[2, 3],
       [5, 2]])

In [ ]:
d=np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

슬라이싱

In [ ]:
print(d[1][2])
print(d[1,2])
print(d[1:,3:])

5
5
[[6 7]
 [9 9]]


배열의 크기

In [ ]:
d =  np.array([2,3,4,5,6])
print(d.ndim)
print(d.shape)

1
(5,)


원소 유형 확인

In [ ]:
d =  np.array([2,3,4,5,6])
print(d.dtype)

d =  np.array([4.1, 5.3, 6.5])
print(d.dtype)


int64
float64


형변환

In [ ]:
data = np.array([1,5])
print(data.dtype)
data.astype('float64')


int64


array([1., 5.])

In [ ]:
data.astype('int64')

array([1, 5])

넘파이 함수

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.ones((2,3))
print(a)
b = np.transpose(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


배열의 사칙연산

In [ ]:
arr1 =np.array([[2,3,4],[6,7,8]])
arr2 =np.array([[12,23,14],[36,47,58]])

In [ ]:
arr1+arr2

array([[14, 26, 18],
       [42, 54, 66]])

In [ ]:
arr1*arr2

array([[ 24,  69,  56],
       [216, 329, 464]])

In [ ]:
arr1/arr2

array([[0.16666667, 0.13043478, 0.28571429],
       [0.16666667, 0.14893617, 0.13793103]])

In [ ]:
arr3=np.array([100,200,300])

In [ ]:
print(arr1)
print(arr1.shape)
print(arr3)
print(arr3.shape)
arr1+arr3         #브로드캐스팅

[[2 3 4]
 [6 7 8]]
(2, 3)
[100 200 300]
(3,)


array([[102, 203, 304],
       [106, 207, 308]])

In [ ]:
arr4 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr4.shape)
print(arr1.shape)
arr1+arr4

(10,)
(2, 3)


ValueError: ignored

In [ ]:
arr5 = np.array([[9],[3]])
print(arr5.shape)
arr5+arr1

(2, 1)


array([[11, 12, 13],
       [ 9, 10, 11]])

리스트와 배열의 차이

In [ ]:
d=np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
d_list = [[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]]
print(type(d_list))

d_list[:2] = 0

<class 'list'>


TypeError: ignored

In [ ]:
d[:2]=0
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [5 7 8 9 9]]


인덱싱과 슬라이싱

In [ ]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4[:5] 

array([0, 1, 2, 3, 4])

In [ ]:
arr4[-3:]

array([7, 8, 9])

In [ ]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr1[1,2]

8

In [ ]:
arr1[:,2]

array([4, 8])

설문지 데이터 전처리

In [ ]:
import usecsv
import numpy as np
quest = np.array(usecsv.switch(usecsv.opencsv("quest.csv")))
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [ ]:
quest[quest>5] = 5

In [ ]:
quest

array([[1., 2., 1., 2., 2.],
       [1., 3., 2., 3., 2.],
       [1., 4., 3., 3., 3.],
       [2., 5., 4., 4., 4.],
       [2., 5., 5., 2., 5.],
       [3., 5., 4., 2., 5.],
       [3., 5., 4., 1., 5.],
       [3., 5., 5., 1., 3.]])

In [ ]:
usecsv.writecsv("result.csv", list(quest))

넘파이로 사업성 분석하기

In [ ]:
import numpy as np
discount = .05
cashflow = 100

def presentvalue(n):
  return (cashflow/((1+discount)**n))

print(presentvalue(1))
print(presentvalue(2))

95.23809523809524
90.70294784580499


In [ ]:
for i in range(20):
  print(presentvalue(i))

100.0
95.23809523809524
90.70294784580499
86.3837598531476
82.27024747918819
78.35261664684589
74.62153966366274
71.06813301301213
67.6839362028687
64.46089162177971
61.39132535407592
58.46792890864373
55.68374181775592
53.03213506452945
50.506795299551854
48.101709809096995
45.811152199140004
43.62966876108571
41.5520654867483
39.57339570166504


놀이공원의 사업성 분석하기

In [ ]:
loss = [-750, -250]
profit = [100]*18
cf = loss+profit
cf

[-750,
 -250,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100]

In [ ]:
len(cf)

20

In [ ]:
cashflow = np.array(cf)

In [ ]:
pip install numpy-financial

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy_financial as npf

npv = npf.npv(0.045, cashflow)
npv

174.4011295118405

In [ ]:
irr = npf.irr(cashflow)
irr

0.06434936937255586

데이터 프레임

In [ ]:
import pandas as pd
data = {'name':['Mark','Jane','Chris','Ryan'],
        'age':[33,32,44,42],
        'score':[91.3, 83.4, 77.5, 87.7]}
df = pd.DataFrame(data)
df

name  age  score
0   Mark   33   91.3
1   Jane   32   83.4
2  Chris   44   77.5
3   Ryan   42   87.7

In [ ]:
df2 = pd.DataFrame()
df2['name'] = ['Mark','Jane','Chris','Ryan']
df2['age'] = [33,32,44,42]
df2['score'] = [91.3, 83.4, 77.5, 87.7]
df2

name  age  score
0   Mark   33   91.3
1   Jane   32   83.4
2  Chris   44   77.5
3   Ryan   42   87.7

In [ ]:
df.sum()

name     MarkJaneChrisRyan
age                    151
score                339.9
dtype: object

In [ ]:
df.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


age      37.750
score    84.975
dtype: float64

In [ ]:
print(df.age)
print(df['age'])

0    33
1    32
2    44
3    42
Name: age, dtype: int64
0    33
1    32
2    44
3    42
Name: age, dtype: int64


csv 파일 불러와 데이터프레임으로 만들기

In [3]:
import pandas as pd
import re
df = pd.read_csv('apt.csv')

UnicodeDecodeError: ignored

In [4]:
df = pd.read_csv('apt.csv', encoding = 'cp949')
len(df)

2141

In [5]:
df.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명  
0  1997   경강로2539번길 8  
1  1997   경강로2539번길 8  
2  2005  경강로2539번길 22  
3  2005  경강로2539번길 22  
4  2005  경강로2539번길 22

In [6]:
df.tail()

지역   번지   본번  부번        아파트      면적    계약년월  계약일     가격   층  \
2136  경기도 광명시 철산동  625  625   0  도덕파크타운2단지   39.65  201910   30  28700   6   
2137  경기도 광명시 철산동  629  629   0       두산위브   59.81  201910    9  46700  12   
2138  경기도 광명시 철산동  629  629   0       두산위브   59.81  201910    9  46500   8   
2139  경기도 광명시 철산동  629  629   0       두산위브  114.99  201910   12  65000  11   
2140  경기도 광명시 철산동  627  627   0      롯데낙천대   59.94  201910   17  43500   1   

      건축년도       도로명  
2136  2001  가림일로 101  
2137  2007    사성로 91  
2138  2007    사성로 91  
2139  2007    사성로 91  
2140  2005   사성로 123

In [7]:
df.지역

0       강원도 강릉시 견소동
1       강원도 강릉시 견소동
2       강원도 강릉시 견소동
3       강원도 강릉시 견소동
4       강원도 강릉시 견소동
           ...     
2136    경기도 광명시 철산동
2137    경기도 광명시 철산동
2138    경기도 광명시 철산동
2139    경기도 광명시 철산동
2140    경기도 광명시 철산동
Name: 지역, Length: 2141, dtype: object

In [8]:
df[df.면적>130]

지역       번지    본번  부번          아파트        면적    계약년월  계약일  \
6         강원도 강릉시 교동     1982  1982   0  강릉교동롯데캐슬1단지  135.1727  201910   21   
39       강원도 강릉시 남문동    183-2   183   2       삼익그린맨션  164.7540  201910   15   
334      강원도 속초시 금호동      629   629   0     보람레이크더하임  156.7600  201910   16   
433      강원도 원주시 개운동  01월 28일    28   1      원주힐스테이트  133.9912  201910    5   
434      강원도 원주시 개운동  01월 28일    28   1      원주힐스테이트  137.4292  201910   31   
...              ...      ...   ...  ..          ...       ...     ...  ...   
1970  경기도 고양일산서구 탄현동      121   121   0  큰마을대림,현대아파트  134.9700  201910   18   
1971  경기도 고양일산서구 탄현동      121   121   0  큰마을대림,현대아파트  163.4300  201910   19   
2040     경기도 과천시 원문동        4     4   0        래미안슈르  137.2110  201910    3   
2043     경기도 과천시 원문동        4     4   0        래미안슈르  137.2110  201910    8   
2045     경기도 과천시 원문동        4     4   0        래미안슈르  136.6260  201910    9   

          가격   층  건축년도           도로명  
6      34300   9  2009   화부산로99번길 12  
39     21000  12  1992      홍제로 7-17  
334    29500   1  2008  영랑호반길 115-13  
433    26000  16  2006        행구로 54  
434    24000  14  2006        행구로 54  
...      ...  ..   ...           ...  
1970   29800   4  2001       일현로 140  
1971   29500  17  2001       일현로 140  
2040  159000  19  2008        별양로 12  
2043  153500  12  2008        별양로 12  
2045  159000  16  2008        별양로 12  

[110 rows x 12 columns]

In [9]:
df.가격[df.면적>130]

6        34300
39       21000
334      29500
433      26000
434      24000
         ...  
1970     29800
1971     29500
2040    159000
2043    153500
2045    159000
Name: 가격, Length: 110, dtype: int64

In [10]:
df.가격[ (df.면적>130) & (df.가격<15000) ]

862    14900
927    13800
Name: 가격, dtype: int64

In [11]:
df.loc[:10, ['아파트','가격']]

아파트     가격
0              송정한신  10900
1              송정한신  18500
2      송정해변신도브래뉴아파트  25000
3      송정해변신도브래뉴아파트  20600
4      송정해변신도브래뉴아파트  20500
5   강릉 교동 풍림아이원 아파트  29200
6       강릉교동롯데캐슬1단지  34300
7       강릉교동롯데캐슬2단지  32500
8             교동1주공  16200
9             교동1주공  21550
10            교동1주공  21800

In [12]:
df.loc[:, ['아파트','가격']][df.가격>40000]

아파트     가격
382         속초청호아이파크  45800
541         무실e-편한세상  44600
592         원주반곡아이파크  40700
842   온의 롯데캐슬 스카이클래스  44000
843   온의 롯데캐슬 스카이클래스  42900
...              ...    ...
2127       도덕파크타운1단지  42000
2137            두산위브  46700
2138            두산위브  46500
2139            두산위브  65000
2140           롯데낙천대  43500

[396 rows x 2 columns]

In [13]:
df['단가'] = df.가격/df.면적

In [14]:
df.loc[:10,['가격','면적','단가']]

가격        면적          단가
0   10900   59.8000  182.274247
1   18500  116.1750  159.242522
2   25000   84.9900  294.152253
3   20600   84.9900  242.381457
4   20500   84.9900  241.204848
5   29200   84.9964  343.543962
6   34300  135.1727  253.749463
7   32500  118.0686  275.263703
8   16200   59.8900  270.495909
9   21550   84.8400  254.007544
10  21800   84.8400  256.954267

정렬

In [18]:
df.sort_values(by='가격').loc[:,['가격','지역']]

가격                지역
214      950       강원도 동해시 발한동
969     1100       강원도 태백시 동점동
741     1300   강원도 정선군 사북읍 사북리
970     1450       강원도 태백시 동점동
1015    1500  강원도 평창군 대관령면 횡계리
...      ...               ...
2042  149500       경기도 과천시 원문동
2043  153500       경기도 과천시 원문동
2026  155000       경기도 과천시 별양동
2045  159000       경기도 과천시 원문동
2040  159000       경기도 과천시 원문동

[2141 rows x 2 columns]

In [16]:
df.sort_values(by='가격', ascending=False).loc[:,['가격','지역']]

가격                지역
2045  159000       경기도 과천시 원문동
2040  159000       경기도 과천시 원문동
2026  155000       경기도 과천시 별양동
2043  153500       경기도 과천시 원문동
2042  149500       경기도 과천시 원문동
...      ...               ...
1015    1500  강원도 평창군 대관령면 횡계리
970     1450       강원도 태백시 동점동
741     1300   강원도 정선군 사북읍 사북리
969     1100       강원도 태백시 동점동
214      950       강원도 동해시 발한동

[2141 rows x 2 columns]

In [19]:
df[df.가격>40000].sort_values(by='면적').loc[:,['가격','면적','지역']]

가격        면적              지역
2037   91200   54.4800     경기도 과천시 부림동
2115   80500   59.8020     경기도 광명시 일직동
2081   46500   59.8074     경기도 광명시 광명동
2078   43500   59.8074     경기도 광명시 광명동
2138   46500   59.8100     경기도 광명시 철산동
...      ...       ...             ...
1727   63600  173.7700  경기도 고양일산서구 덕이동
1740   63200  173.7700  경기도 고양일산서구 덕이동
1565   89500  238.9914  경기도 고양일산동구 식사동
1564   90000  238.9914  경기도 고양일산동구 식사동
1571  118000  240.1813  경기도 고양일산동구 식사동

[396 rows x 3 columns]

문자열 다루기

In [20]:
df.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명          단가  
0  1997   경강로2539번길 8  182.274247  
1  1997   경강로2539번길 8  159.242522  
2  2005  경강로2539번길 22  294.152253  
3  2005  경강로2539번길 22  242.381457  
4  2005  경강로2539번길 22  241.204848

In [22]:
df.지역.str.find('강릉')

0       4
1       4
2       4
3       4
4       4
       ..
2136   -1
2137   -1
2138   -1
2139   -1
2140   -1
Name: 지역, Length: 2141, dtype: int64

In [23]:
df[df.지역.str.find('강릉')>-1]

지역   번지   본번  부번           아파트        면적    계약년월  계약일     가격  \
0    강원도 강릉시 견소동  202  202   0          송정한신   59.8000  201910    4  10900   
1    강원도 강릉시 견소동  202  202   0          송정한신  116.1750  201910   31  18500   
2    강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.9900  201910    5  25000   
3    강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.9900  201910   12  20600   
4    강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.9900  201910   20  20500   
..           ...  ...  ...  ..           ...       ...     ...  ...    ...   
183  강원도 강릉시 회산동  608  608   0  강릉서희스타힐스리버파크   84.8956  201910   24  24000   
184  강원도 강릉시 회산동  130  130   0      힐스테이트 강릉   84.9925  201910    7  24000   
185  강원도 강릉시 회산동  130  130   0      힐스테이트 강릉   74.9974  201910   19  23000   
186  강원도 강릉시 회산동  130  130   0      힐스테이트 강릉   74.9985  201910   21  24100   
187  강원도 강릉시 회산동  130  130   0      힐스테이트 강릉   74.9974  201910   29  25400   

      층  건축년도           도로명          단가  
0     5  1997   경강로2539번길 8  182.274247  
1    10  1997   경강로2539번길 8  159.242522  
2     6  2005  경강로2539번길 22  294.152253  
3     3  2005  경강로2539번길 22  242.381457  
4     1  2005  경강로2539번길 22  241.204848  
..   ..   ...           ...         ...  
183  10  2017       회산로 344  282.700163  
184   3  2018   회산로383번길 37  282.377857  
185  15  2018   회산로383번길 37  306.677298  
186   6  2018   회산로383번길 37  321.339760  
187  13  2018   회산로383번길 37  338.678408  

[188 rows x 13 columns]

쉼표가 있는 문자를 숫자로 형변환하기

In [24]:
import pandas as pd
df = pd.read_csv("apt_comma.csv", encoding='cp949')


In [25]:
df.가격>100000

TypeError: ignored

In [26]:
df.가격 = df.가격.str.replace(",","").astype('int64')

In [30]:
df[df.가격>200000]

시군구           단지명        면적    계약년월  계약일      가격   층  건축년도  \
10819    경기도 성남분당구 백현동     판교푸르지오그랑블  117.5193  202002   10  243000  15  2011   
11247    경기도 성남수정구 창곡동         래미안위례  134.7200  202002   14  240000   5  2015   
47258    서울특별시 강남구 개포동        개포우성3차  161.0000  202002   11  270000  15  1984   
47260    서울특별시 강남구 개포동      개포주공 1단지   58.0800  202002   14  240000   3  1982   
47262    서울특별시 강남구 개포동      개포주공 1단지   58.0800  202002   15  242000   1  1982   
...                ...           ...       ...     ...  ...     ...  ..   ...   
53281  서울특별시 용산구 용산동5가  용산파크타워(24-0)  137.6300  202002   13  263000  28  2009   
53286    서울특별시 용산구 이촌동        LG한강자이  170.0600  202002   11  315000  14  2003   
53287    서울특별시 용산구 이촌동        LG한강자이  169.4400  202002   14  295000  25  2003   
53297    서울특별시 용산구 이촌동    래미안첼리투스아파트  124.0200  202002   20  279800   4  2015   
53314  서울특별시 용산구 한강로3가     시티파크(2단지)  149.6900  202002    3  235000  27  2007   

             도로명  
10819   동판교로 123  
11247  위례순환로 150  
47258    개포로 307  
47260    개포로 310  
47262    개포로 310  
...          ...  
53281    서빙고로 67  
53286  이촌로64길 15  
53287  이촌로64길 15  
53297    이촌로 310  
53314    서빙고로 31  

[126 rows x 9 columns]

판다스로 통계 데이터 다루기

In [32]:
import re
import pandas as pd
df2 = pd.read_csv('survey.csv')

In [33]:
df2.head()

sex  income  English  jobSatisfaction  stress
0   m    3000      500                5       5
1   f    4000      600                4       4
2   f    5000      700                3       2
3   m    6000      800                2       2
4   m    4000      700                2       5

In [34]:
df2.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


income             4304.217391
English             608.695652
jobSatisfaction       3.304348
stress                3.347826
dtype: float64

In [35]:
df2.income.mean()

4304.217391304348

In [36]:
df2.income.sum()

98997

In [37]:
df2.income.median()

4999.0

In [38]:
df2.describe()

income     English  jobSatisfaction     stress
count    23.000000   23.000000        23.000000  23.000000
mean   4304.217391  608.695652         3.304348   3.347826
std    1019.478341   99.603959         1.258960   1.433644
min    3000.000000  500.000000         1.000000   1.000000
25%    3000.000000  500.000000         2.500000   2.000000
50%    4999.000000  600.000000         3.000000   4.000000
75%    5000.000000  700.000000         4.000000   5.000000
max    6000.000000  800.000000         5.000000   5.000000

In [39]:
df2.income.describe()

count      23.000000
mean     4304.217391
std      1019.478341
min      3000.000000
25%      3000.000000
50%      4999.000000
75%      5000.000000
max      6000.000000
Name: income, dtype: float64

빈도 분석

In [40]:
df2.sex.value_counts()

m    14
f     9
Name: sex, dtype: int64

두 집단 평균 구하기

In [42]:
df2.groupby(df2.sex).mean()

income     English  jobSatisfaction    stress
sex                                                    
f    4333.111111  633.333333         3.666667  3.111111
m    4285.642857  592.857143         3.071429  3.500000